### ISSUE TITLE
two bugs?

### ISSUE THREAD

**Issue by zem007** [HasnainRaz/FC-DenseNet-TensorFlow#10]
I found two issues in the process of running the codes.

1. Model.py (line#: 66), it should be 'def batch_norm(**self**, x, training, name)'?

2. Model.py (line#: 229), it should be
'x = self.dense_block(x, training, **block_nb - 1**, 'up_dense_block_' + str(block_nb))' ?

**Comment by HasnainRaz** [comment]
1. batch_norm is a static method (you can see the @staticmethod decorator on top of it), which means it doesn't require the self argument.

2. The for loop already starts with block_nb - 1, so there is no need to that in the method call.

**Comment by zem007** [comment]
thank you!
