### ISSUE TITLE
HI~Can i ask about this error?

### ISSUE THREAD

**Issue by CHIJUI0128** [HasnainRaz/FC-DenseNet-TensorFlow#21]
i didnt change any word in model.py

Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 38, in main
    FLAGS.batch_size, FLAGS.epochs, FLAGS.learning_rate)
  File "/home/user/CHI_FCN/FC-DenseNet-TensorFlow-master/model.py", line 347, in train
    total_train_cost / train_step, total_val_cost / val_step))
UnboundLocalError: local variable 'train_step' referenced before assignment

**Comment by CHIJUI0128** [comment]
Seems to be a version issue 
which python version you used?
thanks

**Comment by HasnainRaz** [comment]
It seems there is something wrong with your training data. Number of images is incorrect. Please make sure your images are correctly being read and their paths are correct.
